### ISSUE TITLE
Add Serial image grabber

### ISSUE THREAD

**Issue by Bangybug** [jeromeetienne/threex.webar#1]
Hi, 

I thought it would be worth adding a serial image grabber to your code.

That will allow to easily use most of IP-cameras. 

Even a smartphone can be turned into an IP-camera with  "IP Webcam" app, https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en 

I made an example implementation  https://github.com/Bangybug/threex.webar/blob/master/threex.imageserialgrabbing.js in my forked repo https://github.com/Bangybug/threex.webar

**Comment by jeromeetienne** [comment]
hey! thanks for your interest. i dont understand what is a ip webcam.

**Comment by Bangybug** [comment]
IP webcams rarely are accessible via getUserMedia in browsers. Mostly because the lack of virtual webcam drivers. Instead they provide a number of ways of getting the video. My cam has a http service called "shot.jpg" which returns its latest frame captured.

**Comment by JAN4GER** [comment]
hej. good job! congratulation.

I try to use it with stl loader together. with success.

I wonder how to display multiplied 3D objects when I put many cards with markers in camera view.
I thought this code will do so but it does not:

var markers	= jsArucoMarker.detectMarkers(domElement);
markers.forEach(function(marker){
jsArucoMarker.markerToObject3D(marker, markerObject3D);
}

I see correct numbers of markers recognized by value: markers.length
for example 3 or 4, but only the one displays 3D stl object, the one closer to camera.

any idea?
