### ISSUE TITLE
multiplied markers

### ISSUE THREAD

**Issue by JAN4GER** [jeromeetienne/threex.webar#2]
hej. good job! congratulation.

I try to use it with stl loader together. with success.

I wonder how to display multiplied 3D objects when I put many cards with markers in camera view.
I thought this code will do so but it does not:

var markers = jsArucoMarker.detectMarkers(domElement);
markers.forEach(function(marker){
jsArucoMarker.markerToObject3D(marker, markerObject3D);
}

I see correct numbers of markers recognized by value: markers.length
for example 3 or 4, but only the one displays 3D stl object, the one closer to camera.

any idea?

**Comment by jeromeetienne** [comment]
please reask me with learningthree.js office hour.

sorry i dont have time atm, im over the top at work :(

**Comment by jeromeetienne** [comment]
This should happen with the next version of artoolkit. lets hope for the best
